### ISSUE TITLE
Use Kashida (Tatweel) to make mashq elongations

### ISSUE THREAD

**Issue by ClassicAJ** [aliftype/raqq#22]
Perhaps you can code the font such that you can make the mashq elongation function more easily accessible by using the Tatweel character to say that the adjacent (elongatable) letter should be lengthened by one level.

**Comment by khaledhosny** [comment]
I have considered this, but it has several issues:
* It would require adding around 50 more new glyphs for each glyph that can elongate (around 30 glyphs), so that 50 * 30 = 1500 more glyphs
* It can’t handle isolated/final forms properly. E.g. how can one elongate the ص in قص or رص? Adding a tatweel after the ص will tern it into initial/medial form, قصـ and رصـ
* It can’t handle shrinking

So it would too much work and still not be a suitable replacement/alternative to using font variations.

**Comment by ClassicAJ** [comment]
Oh. I might as well try to use something that supports per-rasm custom variables then.

**Comment by khaledhosny** [comment]
If it helps, I often try to apply the variation settings to a full calligraphic syllable (the smallest part of the word with all letters connected) and separate them by spaces e.g. write الدين as ا لد ين then apply the variations to the لد part. This prevents it from breaking shaping and the extra spaces enable the old-style line breaking inside the word seen in Kufic manuscripts.
